//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class isler
    {
        public int isId { get; set; }
        public string isBaslık { get; set; }
        public string isAcıklama { get; set; }
        public Nullable<int> isPersonelid { get; set; }
        public Nullable<System.DateTime> baslanan_ve_iletilentarih { get; set; }
        public Nullable<System.DateTime> bitirilen_ve_yapılantarih { get; set; }
        public Nullable<int> isDurumİd { get; set; }
        public string isYorum { get; set; }
        public Nullable<bool> isOkunma { get; set; }
    
        public virtual durumlar_ durumlar_ { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
