//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.isler = new HashSet<isler>();
        }
    
        public int personelid { get; set; }
        public string personelAdSoyad { get; set; }
        public string personelKullanıcıAd { get; set; }
        public string personelParola { get; set; }
        public Nullable<int> personelBirimid { get; set; }
        public Nullable<int> personelyetkiturid { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isler> isler { get; set; }
        public virtual yetkiTurid yetkiTurid { get; set; }
    }
}
